# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class CodeInterpreter(Protocol):

    @abstractmethod
    def run_code(self, code: str) -> str:
        """
        Execute one Python cell and return a JSON-encoded execution result.
        """
        raise NotImplementedError

    @abstractmethod
    def install_modules(self, modules: str) -> str:
        """
        Add validated pure-Python modules encoded as JSON.
        """
        raise NotImplementedError

    @abstractmethod
    def reset(self) -> str:
        """
        Clear the persistent Python globals used by prior cells.
        """
        raise NotImplementedError

