package pycage

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"fmt"
	"io"
	"sync"
)

// embeddedGuestGz is generated by `make guest`. The component is stored gzipped
// so the module stays `go get`-able: the raw artifact is ~55 MB, the archive
// ~21 MB, and Go's module proxy serves whatever is committed to the tree.
//
//go:embed guest/python.wasm.gz
var embeddedGuestGz []byte

// guestComponent decompresses the embedded CPython component on first use, so
// importing pycage without creating an Engine costs no heap.
var guestComponent = sync.OnceValues(func() ([]byte, error) {
	reader, err := gzip.NewReader(bytes.NewReader(embeddedGuestGz))
	if err != nil {
		return nil, fmt.Errorf("pycage: open embedded guest: %w", err)
	}
	defer reader.Close()
	component, err := io.ReadAll(reader)
	if err != nil {
		return nil, fmt.Errorf("pycage: decompress embedded guest: %w", err)
	}
	return component, nil
})
